languageCode = "fr"
languageName = "French"
weight = 1
title = "Marvin Durot"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Marvin Durot"
  image = "img/avatar.jpg"
  headline = "Développeur web fullstack"
  bio = "Développeur web fullstack"
  links = [
    { email = "mailto:marvin.durot@posteo.me" },
    { github = "https://github.com/marvindurot" },
    { linkedin = "https://linkedin.com/in/marvindurot" },     
    { reddit = "https://reddit.com/user/marvindurot" },
    { stack-overflow = "https://stackoverflow.com/users/userid/marvindurot" },
    { twitter = "https://twitter.com/durotmarvin" },
  ]
